name = "fatelovesirony"
main = "src/index.js"
compatibility_date = "2025-01-01"

routes = [
  { pattern = "fatelovesirony.com", custom_domain = true },
  { pattern = "www.fatelovesirony.com", custom_domain = true },
]

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "fatelovesirony"
database_id = "865993a9-80d2-4d62-aeb7-2f8762dafdbb"